namespace XeniaManager.Core.Models.Files.Bindings;

/// <summary>
/// Enumeration of virtual key codes for keyboard and mouse inputs.
/// Based on Xenia's kKeyMap and Windows Virtual Key codes.
/// </summary>
public enum VirtualKeyCode : ushort
{
    // Not a valid key
    [BindingName("None")] None = 0x00,

    // Mouse buttons
    [BindingName("LMouse", "LClick")] LButton = 0x01,
    [BindingName("RMouse", "RClick")] RButton = 0x02,
    [BindingName("MMouse", "MClick")] MButton = 0x04,
    [BindingName("Mouse4", "XButton1")] Mouse4 = 0x05,
    [BindingName("Mouse5", "XButton2")] Mouse5 = 0x06,
    [BindingName("MWheelUp")] MWheelUp = 0x0E,
    [BindingName("MWheelDown")] MWheelDown = 0x0F,

    // Modifier keys
    [BindingName("LShift", "Shift")] LShift = 0xA0,
    [BindingName("RShift")] RShift = 0xA1,
    [BindingName("LControl", "Control", "Ctrl")] LControl = 0xA2,
    [BindingName("RControl")] RControl = 0xA3,
    [BindingName("LAlt", "Alt")] LAlt = 0xA4,
    [BindingName("RAlt", "AltGr")] RAlt = 0xA5,
    [BindingName("CapsLock")] CapsLock = 0x14,

    // Special keyboard keys
    [BindingName("Backspace")] Back = 0x08,
    [BindingName("Tab")] Tab = 0x09,
    [BindingName("Enter", "Return")] Enter = 0x0D,
    [BindingName("REnter", "NumEnter", "Separator")] REnter = 0x6C,
    [BindingName("Escape")] Escape = 0x1B,
    [BindingName("Space")] Space = 0x20,
    [BindingName("PgUp", "Prior")] PgUp = 0x21,
    [BindingName("PgDown", "Next")] PgDown = 0x22,
    [BindingName("End")] End = 0x23,
    [BindingName("Home")] Home = 0x24,
    [BindingName("Delete")] Delete = 0x2E,
    [BindingName("Insert")] Insert = 0x2D,

    // Arrow keys
    [BindingName("Left")] Left = 0x25,
    [BindingName("Up")] Up = 0x26,
    [BindingName("Right")] Right = 0x27,
    [BindingName("Down")] Down = 0x28,

    // Number row
    [BindingName("0")] D0 = 0x30,
    [BindingName("1")] D1 = 0x31,
    [BindingName("2")] D2 = 0x32,
    [BindingName("3")] D3 = 0x33,
    [BindingName("4")] D4 = 0x34,
    [BindingName("5")] D5 = 0x35,
    [BindingName("6")] D6 = 0x36,
    [BindingName("7")] D7 = 0x37,
    [BindingName("8")] D8 = 0x38,
    [BindingName("9")] D9 = 0x39,

    // Letters
    [BindingName("A")] A = 0x41,
    [BindingName("B")] B = 0x42,
    [BindingName("C")] C = 0x43,
    [BindingName("D")] D = 0x44,
    [BindingName("E")] E = 0x45,
    [BindingName("F")] F = 0x46,
    [BindingName("G")] G = 0x47,
    [BindingName("H")] H = 0x48,
    [BindingName("I")] I = 0x49,
    [BindingName("J")] J = 0x4A,
    [BindingName("K")] K = 0x4B,
    [BindingName("L")] L = 0x4C,
    [BindingName("M")] M = 0x4D,
    [BindingName("N")] N = 0x4E,
    [BindingName("O")] O = 0x4F,
    [BindingName("P")] P = 0x50,
    [BindingName("Q")] Q = 0x51,
    [BindingName("R")] R = 0x52,
    [BindingName("S")] S = 0x53,
    [BindingName("T")] T = 0x54,
    [BindingName("U")] U = 0x55,
    [BindingName("V")] V = 0x56,
    [BindingName("W")] W = 0x57,
    [BindingName("X")] X = 0x58,
    [BindingName("Y")] Y = 0x59,
    [BindingName("Z")] Z = 0x5A,

    // Function keys
    [BindingName("F1")] F1 = 0x70,
    [BindingName("F2")] F2 = 0x71,
    [BindingName("F3")] F3 = 0x72,
    [BindingName("F4")] F4 = 0x73,
    [BindingName("F5")] F5 = 0x74,
    [BindingName("F6")] F6 = 0x75,
    [BindingName("F7")] F7 = 0x76,
    [BindingName("F8")] F8 = 0x77,
    [BindingName("F9")] F9 = 0x78,
    [BindingName("F10")] F10 = 0x79,
    [BindingName("F11")] F11 = 0x7A,
    [BindingName("F12")] F12 = 0x7B,
    [BindingName("F13")] F13 = 0x7C,
    [BindingName("F14")] F14 = 0x7D,
    [BindingName("F15")] F15 = 0x7E,
    [BindingName("F16")] F16 = 0x7F,
    [BindingName("F17")] F17 = 0x80,
    [BindingName("F18")] F18 = 0x81,
    [BindingName("F19")] F19 = 0x82,
    [BindingName("F20")] F20 = 0x83,
    [BindingName("F21")] F21 = 0x84,
    [BindingName("F22")] F22 = 0x85,
    [BindingName("F23")] F23 = 0x86,
    [BindingName("F24")] F24 = 0x87,

    // Numpad keys
    [BindingName("Num0")] Numpad0 = 0x60,
    [BindingName("Num1")] Numpad1 = 0x61,
    [BindingName("Num2")] Numpad2 = 0x62,
    [BindingName("Num3")] Numpad3 = 0x63,
    [BindingName("Num4")] Numpad4 = 0x64,
    [BindingName("Num5")] Numpad5 = 0x65,
    [BindingName("Num6")] Numpad6 = 0x66,
    [BindingName("Num7")] Numpad7 = 0x67,
    [BindingName("Num8")] Numpad8 = 0x68,
    [BindingName("Num9")] Numpad9 = 0x69,
    [BindingName("Num+")] NumpadAdd = 0x6B,
    [BindingName("Num-")] NumpadSubtract = 0x6D,
    [BindingName("Num*")] NumpadMultiply = 0x6A,
    [BindingName("Num/")] NumpadDivide = 0x6F,
    [BindingName("Num.")] NumpadDecimal = 0x6E,
    [BindingName("NumEnter")] NumpadEnter = 0x6C,
    [BindingName("NumLock")] NumLock = 0x90,

    // Punctuation and symbols
    [BindingName(";", ":")] Oem1 = 0xBA,
    [BindingName("=")] OemPlus = 0xBB,
    [BindingName("+")] OemPlusPlus = 0xBB,
    [BindingName(",", "<")] OemComma = 0xBC,
    [BindingName("-")] OemMinus = 0xBD,
    [BindingName("_")] OemMinusUnder = 0xBD,
    [BindingName(".", ">")] OemPeriod = 0xBE,
    [BindingName("/")] Oem2 = 0xBF,
    [BindingName("?")] Oem2Question = 0xBF,
    [BindingName("'")] Oem3 = 0xC0,
    [BindingName("@")] Oem3At = 0xC0,
    [BindingName("`")] Oem8 = 0xDF,
    [BindingName("[")] Oem4 = 0xDB,
    [BindingName("{")] Oem4Brace = 0xDB,
    [BindingName("\\")] Oem5 = 0xDC,
    [BindingName("|")] Oem5Pipe = 0xDC,
    [BindingName("]")] Oem6 = 0xDD,
    [BindingName("}")] Oem6Brace = 0xDD,
    [BindingName("#")] Oem7 = 0xDE,
    [BindingName("\"")] Oem7Quote = 0xDE,
}