namespace XeniaManager.Core.GPULibrary;

public enum NvApi_Status : int
{
    OK = 0,
    Error = -1,
    LibraryNotFound = -2,
    NoImplementation = -3,
    ApiNotInitialized = -4,
    InvalidArgument = -5,
    NvidiaDeviceNotFound = -6,
    EndEnumeration = -7,
    InvalidHandle = -8,
    IncompatibleStructVersion = -9,
    HandleInvalidated = -10,
    OpenGLContextNotCurrent = -11,
    InvalidPointer = -14,
    NoGlExpert = -12,
    InstrumentationDisabled = -13,
    NoGlNsight = -15,
    ExpectedLogicalGpuHandle = -100,
    ExpectedPhysicalGpuHandle = -101,
    ExpectedDisplayHandle = -102,
    InvalidCombination = -103,
    NotSupported = -104,
    PortIdNotFound = -105,
    ExpectedUnattachedDisplayHandle = -106,
    InvalidPerfLevel = -107,
    DeviceBusy = -108,
    NvPersistFileNotFound = -109,
    PersistDataNotFound = -110,
    ExpectedTvDisplay = -111,
    ExpectedTvDisplayOnDconnector = -112,
    NoActiveSliTopology = -113,
    SliRenderingModeNotAllowed = -114,
    ExpectedDigitalFlatPanel = -115,
    ArgumentExceedMaxSize = -116,
    DeviceSwitchingNotAllowed = -117,
    TestingClocksNotSupported = -118,
    UnknownUnderscanConfig = -119,
    TimeoutReconfiguringGpuTopo = -120,
    DataNotFound = -121,
    ExpectedAnalogDisplay = -122,
    NoVidLink = -123,
    RequiresReboot = -124,
    InvalidHybridMode = -125,
    MixedTargetTypes = -126,
    Syswow64NotSupported = -127,
    ImplicitSetGpuTopologyChangeNotAllowed = -128,
    RequestUserToCloseNonMigratableApps = -129,
    OutOfMemory = -130,
    WasStillDrawing = -131,
    FileNotFound = -132,
    TooManyUniqueStateObjects = -133,
    InvalidCall = -134,
    D3D10_1LibraryNotFound = -135,
    FunctionNotFound = -136,
    InvalidUserPrivilege = -137,
    ExpectedNonPrimaryDisplayHandle = -138,
    ExpectedComputeGpuHandle = -139,
    StereoNotInitialized = -140,
    StereoRegistryAccessFailed = -141,
    StereoRegistryProfileTypeNotSupported = -142,
    StereoRegistryValueNotSupported = -143,
    StereoNotEnabled = -144,
    StereoNotTurnedOn = -145,
    StereoInvalidDeviceInterface = -146,
    StereoParameterOutOfRange = -147,
    StereoFrustumAdjustModeNotSupported = -148,
    TopoNotPossible = -149,
    ModeChangeFailed = -150,
    D3D11LibraryNotFound = -151,
    InvalidAddress = -152,
    StringTooSmall = -153,
    MatchingDeviceNotFound = -154,
    DriverRunning = -155,
    DriverNotRunning = -156,
    ErrorDriverReloadRequired = -157,
    SetNotAllowed = -158,
    AdvancedDisplayTopologyRequired = -159,
    SettingNotFound = -160,
    SettingSizeTooLarge = -161,
    TooManySettingsInProfile = -162,
    ProfileNotFound = -163,
    ProfileNameInUse = -164,
    ProfileNameEmpty = -165,
    ExecutableNotFound = -166,
    ExecutableAlreadyInUse = -167,
    DatatypeMismatch = -168,
    ProfileRemoved = -169,
    UnregisteredResource = -170,
    IdOutOfRange = -171,
    DisplayConfigValidationFailed = -172,
    DpmstChanged = -173,
    InsufficientBuffer = -174,
    AccessDenied = -175,
    MosaicNotActive = -176,
    ShareResourceRelocated = -177,
    RequestUserToDisableDwm = -178,
    D3DDeviceLost = -179,
    InvalidConfiguration = -180,
    StereoHandshakeNotDone = -181,
    ExecutablePathIsAmbiguous = -182,
    DefaultStereoProfileIsNotDefined = -183,
    DefaultStereoProfileDoesNotExist = -184,
    ClusterAlreadyExists = -185,
    DpmstDisplayIdExpected = -186,
    InvalidDisplayId = -187,
    StreamIsOutOfSync = -188,
    IncompatibleAudioDriver = -189,
    ValueAlreadySet = -190,
    Timeout = -191,
    GpuWorkstationFeatureIncomplete = -192,
    StereoInitActivationNotDone = -193,
    SyncNotActive = -194,
    SyncMasterNotFound = -195,
    InvalidSyncTopology = -196,
    EcidSignAlgoUnsupported = -197,
    EcidKeyVerificationFailed = -198,
    FirmwareOutOfDate = -199,
    FirmwareRevisionNotSupported = -200,
    LicenseCallerAuthenticationFailed = -201,
    D3DDeviceNotRegistered = -202,
    ResourceNotAcquired = -203,
    TimingNotSupported = -204,
    HdcpEncryptionFailed = -205,
    PclkLimitationFailed = -206,
    NoConnectorFound = -207,
    HdcpDisabled = -208,
    ApiInUse = -209,
    NvidiaDisplayNotFound = -210,
    PrivSecViolation = -211,
    IncorrectVendor = -212,
    DisplayInUse = -213,
    UnsupportedConfigNonHdcpHmd = -214,
    MaxDisplayLimitReached = -215,
    InvalidDirectModeDisplay = -216,
    GpuInDebugMode = -217,
    D3DContextNotFound = -218,
    StereoVersionMismatch = -219,
    GpuNotPowered = -220,
    ErrorDriverReloadInProgress = -221,
    WaitForHwResource = -222,
    RequireFurtherHdcpAction = -223,
    DisplayMuxTransitionFailed = -224,
    InvalidDscVersion = -225,
    InvalidDscSliceCount = -226,
    InvalidDscOutputBpp = -227,
    FailedToLoadFromDriverStore = -228,
    NoVulkan = -229,
    RequestPending = -230,
    ResourceInUse = -231,
    InvalidImage = -232,
    InvalidPtx = -233,
    NvLinkUncorrectable = -234,
    JitCompilerNotFound = -235,
    InvalidSource = -236,
    IllegalInstruction = -237,
    InvalidPc = -238,
    LaunchFailed = -239,
    NotPermitted = -240,
    CallbackAlreadyRegistered = -241,
    CallbackNotFound = -242,
    InvalidOutputWireFormat = -243
}

internal enum DRS_SETTING_TYPE : int
{
    NVDRS_DWORD_TYPE,
    NVDRS_BINARY_TYPE,
    NVDRS_STRING_TYPE,
    NVDRS_WSTRING_TYPE
}

internal enum DRS_SETTING_LOCATION : int
{
    NVDRS_CURRENT_PROFILE_LOCATION,
    NVDRS_GLOBAL_PROFILE_LOCATION,
    NVDRS_BASE_PROFILE_LOCATION,
    NVDRS_DEFAULT_PROFILE_LOCATION
}

[Flags]
public enum NVDRS_GPU_SUPPORT : uint
{
    None,
    Geforce,
    Quadro,
    Nvs,
}

public enum NvAPI_FunctionId : uint
{
    Initialize = 0x0150E828,
    Unload = 0xD22BDD7E,
    GetErrorMessage = 0x6C2D048C,
    DRS_CreateSession = 0x0694D52E,
    DRS_DestroySession = 0xDAD9CFF8,
    DRS_LoadSettings = 0x375DBD6B,
    DRS_SaveSettings = 0xFCBC7E14,
    DRS_CreateProfile = 0xCC176068,
    DRS_CreateApplication = 0x4347A9DE,
    DRS_DeleteProfile = 0x17093206,
    DRS_GetProfileInfo = 0x61CD6FD6,
    DRS_FindApplicationByName = 0xEEE566B2,
    DRS_FindProfileByName = 0x7E4A9A0B,
    DRS_GetSetting = 0x73BF8338, // 0x8A2CF5F5
    DRS_SetSetting = 0x577DD202 // 0xEA99498D
}