//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaManager.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XeniaManager.Desktop.Resources.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string CompatibilityRating_Gameplay {
            get {
                return ResourceManager.GetString("CompatibilityRating_Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads.
        /// </summary>
        public static string CompatibilityRating_Loads {
            get {
                return ResourceManager.GetString("CompatibilityRating_Loads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playable.
        /// </summary>
        public static string CompatibilityRating_Playable {
            get {
                return ResourceManager.GetString("CompatibilityRating_Playable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CompatibilityRating_Unknown {
            get {
                return ResourceManager.GetString("CompatibilityRating_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplayable.
        /// </summary>
        public static string CompatibilityRating_Unplayable {
            get {
                return ResourceManager.GetString("CompatibilityRating_Unplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Additional Patches.
        /// </summary>
        public static string LibraryGameButton_AddAdditionalPatches {
            get {
                return ResourceManager.GetString("LibraryGameButton_AddAdditionalPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change game path.
        /// </summary>
        public static string LibraryGameButton_ChangeGamePath {
            get {
                return ResourceManager.GetString("LibraryGameButton_ChangeGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Patches.
        /// </summary>
        public static string LibraryGameButton_ConfigurePatches {
            get {
                return ResourceManager.GetString("LibraryGameButton_ConfigurePatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string LibraryGameButton_ContentMenuText {
            get {
                return ResourceManager.GetString("LibraryGameButton_ContentMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string LibraryGameButton_DesktopShortcut {
            get {
                return ResourceManager.GetString("LibraryGameButton_DesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Patches.
        /// </summary>
        public static string LibraryGameButton_DownloadPatches {
            get {
                return ResourceManager.GetString("LibraryGameButton_DownloadPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit game details.
        /// </summary>
        public static string LibraryGameButton_EditGameDetails {
            get {
                return ResourceManager.GetString("LibraryGameButton_EditGameDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Content.
        /// </summary>
        public static string LibraryGameButton_InstallContent {
            get {
                return ResourceManager.GetString("LibraryGameButton_InstallContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Patches.
        /// </summary>
        public static string LibraryGameButton_InstallPatches {
            get {
                return ResourceManager.GetString("LibraryGameButton_InstallPatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulator &amp; Game Path.
        /// </summary>
        public static string LibraryGameButton_LocationMenuText {
            get {
                return ResourceManager.GetString("LibraryGameButton_LocationMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open compatibility page.
        /// </summary>
        public static string LibraryGameButton_OpenCompatibilityPage {
            get {
                return ResourceManager.GetString("LibraryGameButton_OpenCompatibilityPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string LibraryGameButton_PatchesMenuText {
            get {
                return ResourceManager.GetString("LibraryGameButton_PatchesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Xenia Manager.
        /// </summary>
        public static string LibraryGameButton_RemoveGameHeaderText {
            get {
                return ResourceManager.GetString("LibraryGameButton_RemoveGameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Patches.
        /// </summary>
        public static string LibraryGameButton_RemovePatches {
            get {
                return ResourceManager.GetString("LibraryGameButton_RemovePatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        public static string LibraryGameButton_ShortcutMenuText {
            get {
                return ResourceManager.GetString("LibraryGameButton_ShortcutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam.
        /// </summary>
        public static string LibraryGameButton_SteamShortcut {
            get {
                return ResourceManager.GetString("LibraryGameButton_SteamShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View installed content.
        /// </summary>
        public static string LibraryGameButton_ViewInstalledContent {
            get {
                return ResourceManager.GetString("LibraryGameButton_ViewInstalledContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Rating.
        /// </summary>
        public static string LibraryMenuItemShow_CompatibilityRating {
            get {
                return ResourceManager.GetString("LibraryMenuItemShow_CompatibilityRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Title.
        /// </summary>
        public static string LibraryMenuItemShow_GameTitle {
            get {
                return ResourceManager.GetString("LibraryMenuItemShow_GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about Xenia Manager.
        /// </summary>
        public static string MainWindow_AboutTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Library.
        /// </summary>
        public static string MainWindow_GameLibrary {
            get {
                return ResourceManager.GetString("MainWindow_GameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your game library.
        /// </summary>
        public static string MainWindow_GameLibraryTooltip {
            get {
                return ResourceManager.GetString("MainWindow_GameLibraryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MainWindow_Manage {
            get {
                return ResourceManager.GetString("MainWindow_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your installed Xenia.
        /// </summary>
        public static string MainWindow_ManageTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ManageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Xenia.
        /// </summary>
        public static string MainWindow_OpenXenia {
            get {
                return ResourceManager.GetString("MainWindow_OpenXenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Xenia standalone.
        /// </summary>
        public static string MainWindow_OpenXeniaTooltip {
            get {
                return ResourceManager.GetString("MainWindow_OpenXeniaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Xenia Manager settings.
        /// </summary>
        public static string MainWindow_SettingsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (Xenia).
        /// </summary>
        public static string MainWindow_XeniaSettings {
            get {
                return ResourceManager.GetString("MainWindow_XeniaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Xenia settings.
        /// </summary>
        public static string MainWindow_XeniaSettingsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_XeniaSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ManagePage_Install {
            get {
                return ResourceManager.GetString("ManagePage_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string ManagePage_Uninstall {
            get {
                return ResourceManager.GetString("ManagePage_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ManagePage_Update {
            get {
                return ResourceManager.GetString("ManagePage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary: Not Installed.
        /// </summary>
        public static string ManagePage_XeniaCanaryNotInstalled {
            get {
                return ResourceManager.GetString("ManagePage_XeniaCanaryNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the game with default box art?\nPress &apos;Yes&apos; to proceed, or &apos;No&apos; to cancel..
        /// </summary>
        public static string MessageBox_AddGameWithDefaultArtworkText {
            get {
                return ResourceManager.GetString("MessageBox_AddGameWithDefaultArtworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        public static string MessageBox_ConfirmExit {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to uninstall Xenia Canary?\nThis will remove all save files and updates alongside the emulator..
        /// </summary>
        public static string MessageBox_DeleteXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_DeleteXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Xenia Canary.
        /// </summary>
        public static string MessageBox_DeleteXeniaCanaryTitle {
            get {
                return ResourceManager.GetString("MessageBox_DeleteXeniaCanaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently detected Title ID ({0}) is not matching with the selected game&apos;s Title ID ({1}) and can&apos;t be found in the alternative Title ID list.\nDo you want to continue?.
        /// </summary>
        public static string MessageBox_MissmatchedTitleIdText {
            get {
                return ResourceManager.GetString("MessageBox_MissmatchedTitleIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Title ID.
        /// </summary>
        public static string MessageBox_MissmatchedTitleIdTitle {
            get {
                return ResourceManager.GetString("MessageBox_MissmatchedTitleIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MessageBox_Remove {
            get {
                return ResourceManager.GetString("MessageBox_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} content folder?\nThis will get rid of all of the installed title updates, save games etc..
        /// </summary>
        public static string MessageBox_RemoveGameContentText {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} content.
        /// </summary>
        public static string MessageBox_RemoveGameContentTitle {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0}?.
        /// </summary>
        public static string MessageBox_RemoveGameText {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBox_Success {
            get {
                return ResourceManager.GetString("MessageBox_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully installed..
        /// </summary>
        public static string MessageBox_SuccessInstallXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SuccessInstallXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully uninstalled..
        /// </summary>
        public static string MessageBox_SuccessUninstallXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SuccessUninstallXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully updated..
        /// </summary>
        public static string MessageBox_SucessUpdateXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SucessUpdateXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the selected game in the database.\nDo you want to add it with default artwork (Press &quot;Yes&quot;) or retry (Press &quot;No&quot;)?.
        /// </summary>
        public static string MessageBox_UnableFindSelectedGameText {
            get {
                return ResourceManager.GetString("MessageBox_UnableFindSelectedGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the selected game.
        /// </summary>
        public static string MessageBox_UnableFindSelectedGameTitle {
            get {
                return ResourceManager.GetString("MessageBox_UnableFindSelectedGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game.
        /// </summary>
        public static string OpenFileDialog_SelectGameTitle {
            get {
                return ResourceManager.GetString("OpenFileDialog_SelectGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchbox.
        /// </summary>
        public static string Searchbar_PlaceholderText {
            get {
                return ResourceManager.GetString("Searchbar_PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsPage_LanguageSelector {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Manager UI language.
        /// </summary>
        public static string SettingsPage_LanguageSelectorTooltip {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSelectorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_ThemeSelector {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme which will be used by Xenia Manager.
        /// </summary>
        public static string SettingsPage_ThemeSelectorTooltip {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeSelectorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;Manage&quot; page to update these Xenia versions to new version:.
        /// </summary>
        public static string SnackbarPresenter_XeniaUpdateAvailableText {
            get {
                return ResourceManager.GetString("SnackbarPresenter_XeniaUpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia has a new update.
        /// </summary>
        public static string SnackbarPresenter_XeniaUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("SnackbarPresenter_XeniaUpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Queued Frames.
        /// </summary>
        public static string XeniaSettingsPage_AudioMaxQueuedFramesSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioMaxQueuedFramesSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows changing max buffered audio frames to reduce audio delay
        ///NOTE: Minimum is 4.
        /// </summary>
        public static string XeniaSettingsPage_AudioMaxQueuedFramesSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioMaxQueuedFramesSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string XeniaSettingsPage_AudioMuteSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioMuteSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes all audio output.
        /// </summary>
        public static string XeniaSettingsPage_AudioMuteSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioMuteSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string XeniaSettingsPage_AudioSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio System.
        /// </summary>
        public static string XeniaSettingsPage_AudioSystemSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioSystemSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio System.
        /// </summary>
        public static string XeniaSettingsPage_AudioSystemSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioSystemSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dedicated XMA Thread.
        /// </summary>
        public static string XeniaSettingsPage_AudioUseDedicatedXmaThreadSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioUseDedicatedXmaThreadSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables XMA decoding on separate thread
        ///With this option disabled, expect better results, but lower performance.
        /// </summary>
        public static string XeniaSettingsPage_AudioUseDedicatedXmaThreadSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioUseDedicatedXmaThreadSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMA Audio Decoder
        ///(Experimental).
        /// </summary>
        public static string XeniaSettingsPage_AudioXmaDecoderSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmaDecoderSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the usage of new XMA audio decoder.
        /// </summary>
        public static string XeniaSettingsPage_AudioXmaDecoderSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmaDecoderSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMP.
        /// </summary>
        public static string XeniaSettingsPage_AudioXmpSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmpSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Music Player playback
        ///This can fix music in some games.
        /// </summary>
        public static string XeniaSettingsPage_AudioXmpSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmpSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMP Default Volume.
        /// </summary>
        public static string XeniaSettingsPage_AudioXmpVolumeSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmpVolumeSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default music volume if game doesn&apos;t set it.
        /// </summary>
        public static string XeniaSettingsPage_AudioXmpVolumeSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_AudioXmpVolumeSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Display Resolution Height.
        /// </summary>
        public static string XeniaSettingsPage_DisplayCustomInternalResolutionHeightSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayCustomInternalResolutionHeightSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported: 1-1080.
        /// </summary>
        public static string XeniaSettingsPage_DisplayCustomInternalResolutionHeightSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayCustomInternalResolutionHeightSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Display Resolution Width.
        /// </summary>
        public static string XeniaSettingsPage_DisplayCustomInternalResolutionWidthSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayCustomInternalResolutionWidthSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported: 1-1920.
        /// </summary>
        public static string XeniaSettingsPage_DisplayCustomInternalResolutionWidthSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayCustomInternalResolutionWidthSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framerate Limit.
        /// </summary>
        public static string XeniaSettingsPage_DisplayFramerateLimitSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayFramerateLimitSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum frames per second
        ///Defaults to 60 when set to 0 and VSYNC is enabled
        ///0 = Unlimited Frames.
        /// </summary>
        public static string XeniaSettingsPage_DisplayFramerateLimitSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayFramerateLimitSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string XeniaSettingsPage_DisplayFullscreenSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayFullscreenSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the emulator in fullscreen when enabled.
        /// </summary>
        public static string XeniaSettingsPage_DisplayFullscreenSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayFullscreenSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Display Resolution.
        /// </summary>
        public static string XeniaSettingsPage_DisplayInternalResolutionSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayInternalResolutionSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the game that support different resolutions to be rendered in specific resolution
        ///NOTE: The game has to actually support the resolution for this to work. 1280x720 will work in pretty much every game..
        /// </summary>
        public static string XeniaSettingsPage_DisplayInternalResolutionSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayInternalResolutionSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letterbox.
        /// </summary>
        public static string XeniaSettingsPage_DisplayLetterboxSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayLetterboxSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Black Bars
        ///(Letterboxing/Pillarboxing).
        /// </summary>
        public static string XeniaSettingsPage_DisplayLetterboxSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayLetterboxSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string XeniaSettingsPage_DisplaySettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplaySettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Sync.
        /// </summary>
        public static string XeniaSettingsPage_DisplayVSyncSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayVSyncSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables Vertical Sync.
        /// </summary>
        public static string XeniaSettingsPage_DisplayVSyncSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayVSyncSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widescreen.
        /// </summary>
        public static string XeniaSettingsPage_DisplayWidescreenSettingText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayWidescreenSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles between 16:9 and 4:3 aspect ratio
        ///NOTE: Resolutions below 1280x720 run at 4:3 aspect ratio.
        /// </summary>
        public static string XeniaSettingsPage_DisplayWidescreenSettingTooltip {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_DisplayWidescreenSettingTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string XeniaSettingsPage_GeneralSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_GeneralSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string XeniaSettingsPage_GraphicalSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_GraphicalSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacks.
        /// </summary>
        public static string XeniaSettingsPage_HackSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_HackSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string XeniaSettingsPage_StorageSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_StorageSettingsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Input.
        /// </summary>
        public static string XeniaSettingsPage_UserInputSettingsTitleText {
            get {
                return ResourceManager.GetString("XeniaSettingsPage_UserInputSettingsTitleText", resourceCulture);
            }
        }
    }
}
