//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeniaManager.Desktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XeniaManager.Desktop.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay.
        /// </summary>
        public static string CompatibilityRating_Gameplay {
            get {
                return ResourceManager.GetString("CompatibilityRating_Gameplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads.
        /// </summary>
        public static string CompatibilityRating_Loads {
            get {
                return ResourceManager.GetString("CompatibilityRating_Loads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playable.
        /// </summary>
        public static string CompatibilityRating_Playable {
            get {
                return ResourceManager.GetString("CompatibilityRating_Playable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string CompatibilityRating_Unknown {
            get {
                return ResourceManager.GetString("CompatibilityRating_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unplayable.
        /// </summary>
        public static string CompatibilityRating_Unplayable {
            get {
                return ResourceManager.GetString("CompatibilityRating_Unplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string LibraryGameButton_PatchesMenuText {
            get {
                return ResourceManager.GetString("LibraryGameButton_PatchesMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Xenia Manager.
        /// </summary>
        public static string LibraryGameButton_RemoveGameHeaderText {
            get {
                return ResourceManager.GetString("LibraryGameButton_RemoveGameHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility Rating.
        /// </summary>
        public static string LibraryMenuItemShow_CompatibilityRating {
            get {
                return ResourceManager.GetString("LibraryMenuItemShow_CompatibilityRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Title.
        /// </summary>
        public static string LibraryMenuItemShow_GameTitle {
            get {
                return ResourceManager.GetString("LibraryMenuItemShow_GameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows information about Xenia Manager.
        /// </summary>
        public static string MainWindow_AboutTooltip {
            get {
                return ResourceManager.GetString("MainWindow_AboutTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Library.
        /// </summary>
        public static string MainWindow_GameLibrary {
            get {
                return ResourceManager.GetString("MainWindow_GameLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your game library.
        /// </summary>
        public static string MainWindow_GameLibraryTooltip {
            get {
                return ResourceManager.GetString("MainWindow_GameLibraryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string MainWindow_Manage {
            get {
                return ResourceManager.GetString("MainWindow_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your installed Xenia.
        /// </summary>
        public static string MainWindow_ManageTooltip {
            get {
                return ResourceManager.GetString("MainWindow_ManageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Xenia.
        /// </summary>
        public static string MainWindow_OpenXenia {
            get {
                return ResourceManager.GetString("MainWindow_OpenXenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Xenia standalone.
        /// </summary>
        public static string MainWindow_OpenXeniaTooltip {
            get {
                return ResourceManager.GetString("MainWindow_OpenXeniaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_Settings {
            get {
                return ResourceManager.GetString("MainWindow_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Xenia Manager settings.
        /// </summary>
        public static string MainWindow_SettingsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings (Xenia).
        /// </summary>
        public static string MainWindow_XeniaSettings {
            get {
                return ResourceManager.GetString("MainWindow_XeniaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Xenia settings.
        /// </summary>
        public static string MainWindow_XeniaSettingsTooltip {
            get {
                return ResourceManager.GetString("MainWindow_XeniaSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string ManagePage_Install {
            get {
                return ResourceManager.GetString("ManagePage_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string ManagePage_Uninstall {
            get {
                return ResourceManager.GetString("ManagePage_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ManagePage_Update {
            get {
                return ResourceManager.GetString("ManagePage_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary: Not Installed.
        /// </summary>
        public static string ManagePage_XeniaCanaryNotInstalled {
            get {
                return ResourceManager.GetString("ManagePage_XeniaCanaryNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the game with default box art?\nPress &apos;Yes&apos; to proceed, or &apos;No&apos; to cancel..
        /// </summary>
        public static string MessageBox_AddGameWithDefaultArtworkText {
            get {
                return ResourceManager.GetString("MessageBox_AddGameWithDefaultArtworkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        public static string MessageBox_ConfirmExit {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to uninstall Xenia Canary?\nThis will remove all save files and updates alongside the emulator..
        /// </summary>
        public static string MessageBox_DeleteXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_DeleteXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Xenia Canary.
        /// </summary>
        public static string MessageBox_DeleteXeniaCanaryTitle {
            get {
                return ResourceManager.GetString("MessageBox_DeleteXeniaCanaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBox_Error {
            get {
                return ResourceManager.GetString("MessageBox_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently detected Title ID ({0}) is not matching with the selected game&apos;s Title ID ({1}) and can&apos;t be found in the alternative Title ID list.\nDo you want to continue?.
        /// </summary>
        public static string MessageBox_MissmatchedTitleIdText {
            get {
                return ResourceManager.GetString("MessageBox_MissmatchedTitleIdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched Title ID.
        /// </summary>
        public static string MessageBox_MissmatchedTitleIdTitle {
            get {
                return ResourceManager.GetString("MessageBox_MissmatchedTitleIdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string MessageBox_Remove {
            get {
                return ResourceManager.GetString("MessageBox_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} content folder?\nThis will get rid of all of the installed title updates, save games etc..
        /// </summary>
        public static string MessageBox_RemoveGameContentText {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} content.
        /// </summary>
        public static string MessageBox_RemoveGameContentTitle {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0}?.
        /// </summary>
        public static string MessageBox_RemoveGameText {
            get {
                return ResourceManager.GetString("MessageBox_RemoveGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string MessageBox_Success {
            get {
                return ResourceManager.GetString("MessageBox_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully installed..
        /// </summary>
        public static string MessageBox_SuccessInstallXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SuccessInstallXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully uninstalled..
        /// </summary>
        public static string MessageBox_SuccessUninstallXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SuccessUninstallXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Canary has been successfully updated..
        /// </summary>
        public static string MessageBox_SucessUpdateXeniaCanaryText {
            get {
                return ResourceManager.GetString("MessageBox_SucessUpdateXeniaCanaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the selected game in the database.\nDo you want to add it with default artwork (Press &quot;Yes&quot;) or retry (Press &quot;No&quot;)?.
        /// </summary>
        public static string MessageBox_UnableFindSelectedGameText {
            get {
                return ResourceManager.GetString("MessageBox_UnableFindSelectedGameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the selected game.
        /// </summary>
        public static string MessageBox_UnableFindSelectedGameTitle {
            get {
                return ResourceManager.GetString("MessageBox_UnableFindSelectedGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a game.
        /// </summary>
        public static string OpenFileDialog_SelectGameTitle {
            get {
                return ResourceManager.GetString("OpenFileDialog_SelectGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsPage_LanguageSelector {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia Manager UI language.
        /// </summary>
        public static string SettingsPage_LanguageSelectorTooltip {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageSelectorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsPage_ThemeSelector {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme which will be used by Xenia Manager.
        /// </summary>
        public static string SettingsPage_ThemeSelectorTooltip {
            get {
                return ResourceManager.GetString("SettingsPage_ThemeSelectorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;Manage&quot; page to update these Xenia versions to new version:.
        /// </summary>
        public static string SnackbarPresenter_XeniaUpdateAvailableText {
            get {
                return ResourceManager.GetString("SnackbarPresenter_XeniaUpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xenia has a new update.
        /// </summary>
        public static string SnackbarPresenter_XeniaUpdateAvailableTitle {
            get {
                return ResourceManager.GetString("SnackbarPresenter_XeniaUpdateAvailableTitle", resourceCulture);
            }
        }
    }
}
