name: Update Translation Progress

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update_translation_progress:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: |
          bun init -y
          bun add canvas

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Generate translation progress data
        id: translation-data
        shell: pwsh
        run: |
          $data = python ./scripts/generate_translation_progress.py --json
          echo "data<<EOF" >> $env:GITHUB_OUTPUT
          echo "$data" >> $env:GITHUB_OUTPUT
          echo "EOF" >> $env:GITHUB_OUTPUT

      - name: Generate translation chart
        run: |
          echo '${{ steps.translation-data.outputs.data }}' | bun run ./scripts/generate_translation_chart.js

      - name: Check for chart changes
        id: git-check
        shell: pwsh
        run: |
          $diffOutput = git diff assets/translation-progress.png
          if ($diffOutput) {
            echo "changed=true" >> $env:GITHUB_OUTPUT
          }

      - name: Commit chart
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "214508751+xeniamanager-ci@users.noreply.github.com"
          git config --local user.name "xeniamanager-ci"
          git add assets/translation-progress.png
          git commit -m "chore(localization): Update translation progress chart"

      - name: Push chart
        if: steps.git-check.outputs.changed == 'true'
        run: git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
